import type { Metadata } from "next";
import Nav from "./components/Nav";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import Contacts from "./components/Contacts";
import FlagContextProvider from "./components/FlagContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <FlagContextProvider>
        <html lang="en">
          <body className={`inter.className mx-8 md:mx-16 mt-8`}>
            <Nav />
            {children}
            <Contacts />
            <Footer />
          </body>
        </html>
      </FlagContextProvider>
    </ClerkProvider>
  );
}
